CREATE TABLE simulation_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    record_name VARCHAR(100),
    record_type VARCHAR(50) NOT NULL,
    input_json TEXT NOT NULL,
    output_json TEXT NOT NULL,
    summary_value DOUBLE PRECISION,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_simulation_records_user
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_simulation_records_user_created_at
    ON simulation_records (user_id, created_at);

CREATE INDEX idx_simulation_records_user_record_type
    ON simulation_records (user_id, record_type);
